### ISSUE TITLE
create-wxapp-page 报错

### ISSUE THREAD

**Issue by sukeyYang** [cantonjs/create-wxapp-page#7]
Hello，我执行 命令：yarn create-wxapp-page --name catagory --dir D:\learn\wxapp\wxapp-boilerplate-master\dist\wechat --indent 2 --yes 报错，信息如下：

(node:26908) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open 'C:\Users\Hey_Tree\.config\create-wxapp-page\page\template.wxml'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.readFileSync (fs.js:551:33)
    at filesTypes.forEach.fileType (D:\learn\wxapp\wxapp-boilerplate-master\node_modules\create-wxapp-page\lib\create.js:151:37)
    at Array.forEach (<anonymous>)
    at create (D:\learn\wxapp\wxapp-boilerplate-master\node_modules\create-wxapp-page\lib\create.js:139:13)
    at Object.<anonymous> (D:\learn\wxapp\wxapp-boilerplate-master\node_modules\create-wxapp-page\lib\create.js:288:3)
    at Generator.next (<anonymous>)
    at step (D:\learn\wxapp\wxapp-boilerplate-master\node_modules\create-wxapp-page\lib\create.js:28:191)
    at D:\learn\wxapp\wxapp-boilerplate-master\node_modules\create-wxapp-page\lib\create.js:28:437
    at new Promise (<anonymous>)
(node:26908) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:26908) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Done in 0.66s.

**Comment by flyw** [comment]
same problem

**Comment by flyw** [comment]
problem solved by delete "\Users\__USER_\.config\create-wxapp-page" directory.
this tool will create new one for you.
